CREATE TABLE IF NOT EXISTS "users" (
    id BIGSERIAL PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "worlds" (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    start_year INTEGER NOT NULL,
    current_year INTEGER,
    description VARCHAR(1000),
    user_id BIGINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_world_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT chk_start_year_before_current_year CHECK (start_year <= current_year)
);

CREATE TABLE IF NOT EXISTS "events" (
	id BIGSERIAL PRIMARY KEY,
	title VARCHAR(255) NOT NULL,
	year INTEGER NOT NULL,
	description VARCHAR(1000),
	world_id BIGINT NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT fk_event_world FOREIGN KEY (world_id) REFERENCES worlds(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS figures (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(20) NOT NULL CHECK (type IN ('PERSON', 'FACTION')),
    description VARCHAR(1000),
    world_id BIGINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_figure_world
        FOREIGN KEY (world_id)
        REFERENCES worlds(id)
        ON DELETE CASCADE
);
